apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-tomcat
  namespace: elk  
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /usr/local/tomcat/logs/catalina.*
      fields:
        type: tomcat
      fields_under_root: true

    setup.ilm.enabled: false
    #setup.ilm.rollover_alias: "nginx"
    #setup.ilm.pattern: "{now/d}-000001" 
    setup.template.name: "www-tomcat"
    setup.template.pattern: "www-tomcat-*"

    output.elasticsearch:
      hosts: ["http://172.69.0.69:9200"]
      index: "www-tomcat-%{+yyyy.MM.dd}"
