apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir-example
spec:
  containers:
  - name: write
    image: centos:7
    command: ["bash","-c","for i in {1..100};do echo $i >> /data/hello;sleep 1;done"]
    volumeMounts:
      - name: data
        mountPath: /data

  - name: read
    image: centos:7
    command: ["bash","-c","tail -f /data/hello"]
    volumeMounts:
      - name: data
        mountPath: /data
  restartPolicy: Never
  volumes:
  - name: data
    emptyDir: {}
