kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: k8s-read
rules:
- apiGroups: [""]
  resources: ["pods","services","endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]


---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-k8s
  namespace: default
subjects:
- kind: User
  name: hongxuan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: k8s-read
  apiGroup: rbac.authorization.k8s.io

